--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/VDataStorageSystems
build-by-default: true
branches:
- main
projects:
  VDataStorageSystems:
    path: ""
    model: virion
    type: library
...
